---
# tasks file for install-nginx
- name: create nginx system group
  group:
    name: "{{ nginx_group }}"
    system: yes
    state: present

- name: create nginx system user
  user:
    name: "{{ nginx_user }}"
    system: yes
    shell: "/sbin/nologin"
    group: "{{ nginx_group }}"
    createhome: no

- name: download nginx binary
  become: no
  local_action:
    module: get_url
    url: "{{ nginx_repository }}"
    dest: "/bin/{{ nginx_name }}"
  ignore_errors: true

- name: create nginx directory
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: 0700
  with_items:
    - "{{ nginx_conf_dir }}"

- name: copy nginx config file
  template:
    src: "{{ item }}"
    dest: "{{ nginx_conf_dir }}"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: 0600
  with_fileglob:
    - "templates/nginx/*"

- name: copy systemd service unit
  template:
    src: nginx.service.j2
    dest: /etc/systemd/system/nginx.service
    owner: root
    group: root
    mode: 0644
  notify:
    - reenable nginx service
    - restart nginx
  ignore_errors: true
